name: kingsbazar
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil:
  go_router:
  riverpod:
  flutter_riverpod:
  dio:
  cached_network_image:
  carousel_slider:
  smooth_page_indicator:
  hive:
  hive_flutter:
  shimmer:
  intl: ^0.20.2
  lottie: ^3.3.1
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.5.3
  flutter_svg: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  hive_generator:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/json/